### ISSUE TITLE
你好，我也是参考了那位大神的项目，请问你能实现全局代理吗？

### ISSUE THREAD

**Issue by weqeo** [Hansoncoder/ssDemo#1]
就是不只是在app内部能够实现翻墙，整个手机都能实现。可能是需要改一下port之类的，但是我不会。。。
请问你有什么办法吗？

另外，我发现我的demo里面，访问YouTube的时候，无法加载出视频。。不知道你的会不会有同样的问题？

**Comment by Hansoncoder** [comment]
你可以参考这个项目：https://github.com/Hansoncoder/Potatso.git
